Nama = input("Nama\t\t\t: ")
NIM = input("NIM\t\t\t: ")
KelasParalel = input("Kelas Paralel\t\t: ")
Ttl = input("Tempat/Tanggal Lahir\t: ")
Alamat = input("Alamat\t\t\t: ")
Hobby = input("Hobby\t\t\t: ")
Telp = input("No. HP\t\t\t: ")

print("\n")
print(Nama)
print(NIM)
print(KelasParalel)
print(Ttl)
print(Alamat)
print(Hobby)
print(Telp)