Nama = input("Nama\t\t\t: ")
NIM = input("NIM\t\t\t: ")
KelasParalel = input("Kelas Paralel\t\t: ")
Ttl = input("Tempat/Tanggal Lahir\t: ")
Alamat = input("Alamat\t\t\t: ")
Hobby = input("Hobby\t\t\t: ")
Telp = input("No. HP\t\t\t: ")

print("\nNama                    : ",Nama)
print("NIM                     : ",NIM)
print("Kelas Paralel           : ",KelasParalel)
print("Tempat/Tanggal Lahir    : ",Ttl)
print("Alamat                  : ",Alamat)
print("Hobby                   : ",Hobby)
print("No. HP                  : ",Telp)