a,b,i,j,x,y = input().split()
a = float(a)
b = float(b)
i = float(i)
j = float(j)
x = float(x)
y = float(y)
h = (a-b)*(i/j)-(x+y)
print("%.3f\n" %h)

aa,bb = input().split()
ii,jj = input().split()
xx,yy = input().split()
aa = float(aa)
bb = float(bb)
ii = float(ii)
jj = float(jj)
xx = float(xx)
yy = float(yy)
hh = (aa-bb)*(ii/jj)-(xx+yy)
print("%.3f" %hh)
